<template>
<v-container>
  <v-row justify="center" align-content="center" align="center" class="up_margin">
    <div style="width: 80%;">
    <h1> Welcome! </h1>
    Thank you for your participation!<br><br>

    This task is conducted as a part of a research project in which we try to improve the quality of a crowdsourced dataset(i.e., dataset generated by the collective efforts of people) by introducing appropriate interventions to annotators.<br><br>
    In this task, you will be asked to label a logical relationship of a pair of sentences.

    <br><v-divider/><br>

    <h3 style="color:red;"> NOTES </h3>
    <ul>
      <li> You can label a pair of sentences as much as you want.</li>
      <li> Some of the sentence pairs have correct answers. If you respond incorrectly to the majority of them, you may not be rewarded.</li>
      <li> The final reward will be $0.1 * (# of responses). For example, if you label 100 sentences, you will be paid $10.</li>
      <li> If you want to quit the task, you should click the button "I am done!" at the bottom of the page.<br>
      We will give you a token which you <b>MUST</b> submit to the Amazon MTurk website to get rewards. </li>
      <li> Once you quit the task, you cannot join this task anymore. </li>
      
      <li> It is strongly recommended that you use <a target="_blank" rel="noopener noreferrer" href="https://www.google.com/chrome/">chrome</a> browser in your desktop/laptop for the task. Other browsers or mobile devices may show unexpected behaviors.</li>
    </ul>
    

    <br><br>

    <h4> Contact : <a>hoonhan.d@kaist.ac.kr</a> </h4>
    <h4>Fill in the blank with your MTurk ID and click the button below to proceed to the next step.</h4>
    <v-form
      ref="form"
      v-model="valid"
      style="width:40%;"
    >
    <v-text-field
      v-model="turk_id"
      :rules="idRules"
      label="MTurk ID"
      required
    ></v-text-field>
    </v-form>
  <v-divider/>
    </div>
  </v-row>

  <v-row justify="space-around" align="start" class="up_margin">

    <v-btn
      :disabled="!valid"
      @click="onClickNext"
      color="deep-purple accent-2"
      class="mr-4"
    >
      Next
    </v-btn>
  </v-row>
</v-container>
</template>


<script>
// @ is an alias to /src
import { mapState } from "vuex";

export default {
  name: 'VLanding',
  data: () => ({
    valid: true,
    turk_id: '',
    idRules: [
      v => !!v || 'MTurk ID is required',
    ]
  }),
  computed: {
    ...mapState(['mturk_id'])
  },
  methods: {
    onClickNext: function () {
      const self = this;
      self.$refs.form.validate()
      self.$store.commit('set_mturk_id', self.turk_id.trim())
      self.$helpers.server_call(self, function(self, res){
        if (res.data.user_type != self.$store.state.user_type) {
          throw new Error('Abnormal access to the webpage detected.')
        }
        if (res.data.predone === false){
          self.$router.push('/validation/introduction')
        } else if (res.data.step <= 15) {
          self.$router.push('/validation/annotation')
        } else {
          self.$router.push('/validation/after-done')
        }
      }, "/check_user")
    }
  },
  mounted() {
    this.turk_id = this.mturk_id
    this.$store.commit('set_user_type', 3)
  }
}
</script>

<style scoped>
.up_margin {
  margin-top:2rem;
}
</style>
