# Generated by Django 3.0.8 on 2020-07-28 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='H_Contradiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premise', models.TextField()),
                ('is_done', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='H_Neutral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premise', models.TextField()),
                ('is_done', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Premise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mturk_id', models.TextField()),
                ('premise_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='H_Entailment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Premise')),
                ('written_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.User')),
            ],
        ),
    ]
