# Generated by Django 3.0.8 on 2020-08-05 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premise', models.TextField(max_length=300)),
                ('content', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premise', models.TextField(max_length=300)),
                ('entailment', models.TextField(max_length=300)),
                ('neutral', models.TextField(max_length=300)),
                ('contradiction', models.TextField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='H_Contradiction',
        ),
        migrations.RemoveField(
            model_name='h_entailment',
            name='premise',
        ),
        migrations.RemoveField(
            model_name='h_entailment',
            name='written_by',
        ),
        migrations.DeleteModel(
            name='H_Neutral',
        ),
        migrations.RemoveField(
            model_name='user',
            name='premise_id',
        ),
        migrations.AddField(
            model_name='user',
            name='postSurveyDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='preSurveyDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='step',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='H_Entailment',
        ),
        migrations.AddField(
            model_name='submit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.User'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.User'),
        ),
    ]
