# Generated by Django 3.0.8 on 2020-08-05 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20200805_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joinTime',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
