# Generated by Django 3.0.8 on 2020-08-05 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_user_jointime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='joinTime',
            new_name='time',
        ),
        migrations.AddField(
            model_name='report',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submit',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
