# Generated by Django 3.0.8 on 2020-08-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20200805_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='instrEndTime',
            new_name='introEndTime',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='instrStartTime',
            new_name='introStartTime',
        ),
    ]
