# Generated by Django 3.0.8 on 2020-08-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20200805_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='introStartTime',
        ),
    ]
