# Generated by Django 3.0.8 on 2020-08-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='context_step',
            field=models.IntegerField(default=1),
        ),
    ]
