# Generated by Django 3.0.8 on 2020-08-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_user_context_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='context',
            field=models.TextField(default='', max_length=300),
        ),
    ]
