# Generated by Django 3.0.8 on 2020-08-27 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_submit_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=50)),
                ('alpha', models.IntegerField(default=5)),
                ('ent_cnt', models.IntegerField(default=0)),
                ('ent_pmi', models.FloatField(default=0)),
                ('neu_cnt', models.IntegerField(default=0)),
                ('neu_pmi', models.FloatField(default=0)),
                ('con_cnt', models.IntegerField(default=0)),
                ('con_pmi', models.FloatField(default=0)),
                ('tot_cnt', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='submit',
            name='rule_word',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='introEndTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='joinTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preEndTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
