# Generated by Django 3.0.8 on 2020-08-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20200827_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submit',
            old_name='rule_word',
            new_name='rule_con',
        ),
        migrations.AddField(
            model_name='submit',
            name='rule_ent',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='submit',
            name='rule_neu',
            field=models.CharField(default='', max_length=50),
        ),
    ]
