# Generated by Django 3.0.8 on 2020-08-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_auto_20200827_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='submit',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
