# Generated by Django 3.0.8 on 2020-08-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20200827_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='rule_con',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='issue',
            name='rule_ent',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='issue',
            name='rule_neu',
            field=models.CharField(default='', max_length=50),
        ),
    ]
