# Generated by Django 3.0.8 on 2020-09-05 18:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_auto_20200827_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premise', models.TextField(default='')),
                ('hypothesis', models.TextField(default='')),
                ('answer', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='VUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mturk_id', models.TextField()),
                ('step', models.IntegerField(default=1)),
                ('isQuit', models.BooleanField(default=False)),
                ('joinTime', models.DateTimeField(auto_now_add=True)),
                ('quitTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='VSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('label', models.IntegerField(choices=[(0, 'Error'), (1, 'Entailment'), (2, 'Neutral'), (3, 'Contradiction'), (4, 'Na')], default=0)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.VPair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.User')),
            ],
        ),
    ]
