# Generated by Django 3.0.8 on 2020-09-05 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_vpair_vsubmit_vuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpair',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vsubmit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.VUser'),
        ),
    ]
