# Generated by Django 3.0.8 on 2020-09-09 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_auto_20200905_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ctype',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('premise', models.TextField(max_length=300)),
                ('ctype', models.IntegerField(default=0)),
                ('text', models.TextField(max_length=300)),
                ('cwords', models.TextField(default='', max_length=300)),
                ('cword', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.User')),
            ],
        ),
        migrations.CreateModel(
            name='CIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('premise', models.TextField(default='', max_length=300)),
                ('ctype', models.IntegerField(default=0)),
                ('text', models.TextField(max_length=300)),
                ('cwords', models.TextField(default='', max_length=300)),
                ('cword', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.User')),
            ],
        ),
    ]
