<template>
<v-container>
  <v-row justify="center" align-content="center" align="center" class="up_margin">
    <div style="width: 80%;">
    <h1> Welcome! </h1>
    Thank you for your participation!<br><br>

    This task is conducted as a part of a research project in which we try to improve the quality of crowdsourced dataset(i.e., dataset generated by the collective efforts of people) by introducing appropriate interventions to annotators.<br>
    In this task, you will be asked to write sentences that satisfies a logical relationship to the given premise sentence. For example, given a sentence "Two people have a dinner around the table", you may write "There is no people around the table" to contradict the situation.<br>

    <br><v-divider/><br>

    <h3 style="color:red;"> CAUTIONS </h3>
    <ul>
      <li> This task is expected to take 40 minutes at maximum.</li>
      <li> You can participate in this task only once. Second submission thus will not count.</li>
      <li> You <b>MUST</b> submit the token to Amazon MTurk website to get rewards. The token will be provided after completing the post-task questionnaire.</li>
      <li> If majority of your responses are found to not follow the instructions, you may be rejected for rewards.</li>
      <li> It is strongly recommended that you use <b>chrome</b> browser for the task. Other browsers may show anunexpected behavior.</li>
    </ul>
    <br>

    <h3> STEPS </h3>
    <ol>
      <li> Introduction about the annotation interface </li>
      <li> Pre-task questionnaire </li>
      <li> Annotation </li>
      <li> Post-task questionnaire </li>
    </ol>
    <br><br>

    <h4> Contact : <a>hoonhan.d@kaist.ac.kr</a> </h4>
    <h4>Fill in the blank with your MTurk ID and click the button below to proceed to the next step.</h4>
    <v-form
      ref="form"
      v-model="valid"
      style="width:40%;"
    >
    <v-text-field
      v-model="turk_id"
      :rules="idRules"
      label="MTurk ID"
      required
    ></v-text-field>
    </v-form>
  <v-divider/>
    </div>
  </v-row>

  <v-row justify="space-around" align="start" class="up_margin">

    <v-btn
      :disabled="!valid"
      @click="onClickNext"
      color="deep-purple accent-2"
      class="mr-4"
    >
      Next
    </v-btn>
  </v-row>
</v-container>
</template>


<script>
// @ is an alias to /src
import { mapState } from "vuex";

export default {
  name: 'Landing',
  data: () => ({
    valid: true,
    turk_id: '',
    idRules: [
      v => !!v || 'MTurk ID is required',
    ]
  }),
  computed: {
    ...mapState(['mturk_id'])
  },
  methods: {
    onClickNext: function () {
      const self = this;
      self.$refs.form.validate()
      self.$store.commit('set_mturk_id', self.turk_id.trim())
      self.$helpers.server_call(self, function(self, res){
        if (res.data.predone === false){
          self.$router.push('/introduction')
        } else if (res.data.step <= 20) {
          self.$router.push('/annotation')
        } else {
          self.$router.push('/after-done')
        }
      }, "/check_user")
    }
  },
  mounted() {
    this.turk_id = this.mturk_id
  }
}
</script>

<style scoped>
.up_margin {
  margin-top:2rem;
}
</style>
